import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextValue {
  lang: Language;
  dir: 'ltr' | 'rtl';
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ── Nav ──────────────────────────────────────────────────────────────────
    'nav.home': 'Home',
    'nav.marketplace': 'Marketplace',
    'nav.projects': 'Projects',
    'nav.rfq': 'Get Quotes',
    'nav.signin': 'Sign In',
    'nav.signup': 'Get Started',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Sign Out',
    'nav.messages': 'Messages',
    'nav.notifications': 'Notifications',
    'nav.admin': 'Admin Panel',
    'nav.ai': 'AI Assistant',
    // ── Hero ─────────────────────────────────────────────────────────────────
    'hero.badge': 'AI-Powered Construction OS',
    'hero.title': 'Build Smarter. Connect Everyone.',
    'hero.subtitle': 'BuildHub connects homeowners, contractors, engineers, architects, and suppliers in one intelligent ecosystem — from planning to completion.',
    'hero.cta.primary': 'Start Your Project',
    'hero.cta.secondary': 'Explore Marketplace',
    // ── Stats ────────────────────────────────────────────────────────────────
    'stats.users': 'Registered Users',
    'stats.projects': 'Active Projects',
    'stats.providers': 'Verified Providers',
    'stats.satisfaction': 'Satisfaction Rate',
    // ── Features ─────────────────────────────────────────────────────────────
    'features.badge': 'Features',
    'features.title': 'Everything You Need to Build',
    'features.subtitle': 'One platform for every stage of your construction journey',
    'features.marketplace.title': 'Smart Marketplace',
    'features.marketplace.desc': 'Browse thousands of products across materials, furniture, HVAC, and more with full specs and verified reviews.',
    'features.rfq.title': 'RFQ Engine',
    'features.rfq.desc': 'Post your requirements and receive competitive quotations from verified providers, then compare side by side.',
    'features.ai.title': 'AI Assistant Suite',
    'features.ai.desc': 'Get instant cost estimates, quantity surveys, material recommendations, and risk assessments powered by AI.',
    'features.pm.title': 'Project Management',
    'features.pm.desc': 'Track timelines, milestones, budgets, and team tasks in a unified workspace designed for construction.',
    'features.matching.title': 'Smart Matching',
    'features.matching.desc': 'Our algorithm surfaces the best-fit contractors and suppliers based on location, ratings, and your budget.',
    'features.messaging.title': 'Real-time Collaboration',
    'features.messaging.desc': 'Chat, share files, exchange quotations, and get notified instantly — all within the platform.',
    // ── How it works ─────────────────────────────────────────────────────────
    'how.badge': 'How It Works',
    'how.title': 'From Idea to Completion in 4 Steps',
    'how.step1.title': 'Create Your Project',
    'how.step1.desc': 'Define your project scope, budget, and timeline. Upload drawings and BOQs.',
    'how.step2.title': 'Post an RFQ',
    'how.step2.desc': 'Describe your requirements and receive competitive quotations from verified providers.',
    'how.step3.title': 'Compare & Choose',
    'how.step3.desc': 'Compare providers side by side on price, timeline, rating, and experience.',
    'how.step4.title': 'Manage & Complete',
    'how.step4.desc': 'Track progress, manage payments, communicate with your team, and complete your project.',
    // ── Roles ────────────────────────────────────────────────────────────────
    'roles.badge': 'Who It\'s For',
    'roles.title': 'Built for Every Stakeholder',
    'roles.homeowner': 'Homeowner',
    'roles.homeowner.desc': 'Create projects, manage budgets, hire professionals, and track progress from one dashboard.',
    'roles.homeowner.cta': 'Start as Homeowner',
    'roles.contractor': 'Contractor',
    'roles.contractor.desc': 'Receive RFQs, submit quotations, manage your team, and grow your business.',
    'roles.contractor.cta': 'Join as Contractor',
    'roles.engineer': 'Engineer',
    'roles.engineer.desc': 'Showcase your expertise, collaborate on projects, and manage your portfolio.',
    'roles.engineer.cta': 'Join as Engineer',
    'roles.architect': 'Architect',
    'roles.architect.desc': 'Present your designs, connect with clients, and manage project documentation.',
    'roles.architect.cta': 'Join as Architect',
    'roles.supplier': 'Supplier',
    'roles.supplier.desc': 'List your products, receive orders, and reach thousands of construction professionals.',
    'roles.supplier.cta': 'Join as Supplier',
    'roles.pm': 'Project Manager',
    'roles.pm.desc': 'Oversee multiple projects, coordinate teams, and deliver on time and budget.',
    'roles.pm.cta': 'Join as PM',
    // ── Testimonials ─────────────────────────────────────────────────────────
    'testimonials.badge': 'Testimonials',
    'testimonials.title': 'Trusted by Thousands',
    'testimonials.subtitle': 'See what our users say about BuildHub',
    'testimonials.1.text': 'BuildHub saved me weeks of searching for contractors. The side-by-side comparison made choosing so easy.',
    'testimonials.1.name': 'Layla Ahmed',
    'testimonials.1.role': 'Homeowner, Cairo',
    'testimonials.2.text': 'As a contractor, the RFQ engine brings me qualified leads every week. My business has grown 40% since joining.',
    'testimonials.2.name': 'Khaled Mostafa',
    'testimonials.2.role': 'General Contractor, Alexandria',
    'testimonials.3.text': 'The AI cost estimator is incredibly accurate. It\'s now the first tool I use on every new project.',
    'testimonials.3.name': 'Nour Hassan',
    'testimonials.3.role': 'Civil Engineer, Giza',
    // ── CTA Banner ───────────────────────────────────────────────────────────
    'cta.title': 'Ready to Build Smarter?',
    'cta.subtitle': 'Join thousands of homeowners, contractors, and professionals already using BuildHub.',
    'cta.primary': 'Get Started Free',
    'cta.secondary': 'Learn More',
    // ── Footer ───────────────────────────────────────────────────────────────
    'footer.tagline': 'The AI-powered construction operating system for the Middle East.',
    'footer.platform': 'Platform',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.blog': 'Blog',
    'footer.press': 'Press',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved.',
    // ── Auth ─────────────────────────────────────────────────────────────────
    'auth.signin': 'Sign In',
    'auth.signup': 'Create Account',
    'auth.role.select': 'I am a...',
    'auth.role.prompt': 'Select your role to get started',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.otp': 'Verification Code',
    'auth.otp.sent': 'We sent a 6-digit code to your phone',
    'auth.continue': 'Continue',
    'auth.complete_setup': 'Complete Setup',
    'auth.have.account': 'Already have an account?',
    'auth.no.account': "Don't have an account?",
    'auth.welcome': 'Welcome to BuildHub',
    'auth.tagline': 'The smarter way to build',
    'auth.or': 'or continue with',
    'auth.forgot': 'Forgot password?',
    // ── Dashboard ────────────────────────────────────────────────────────────
    'dash.overview': 'Overview',
    'dash.projects': 'My Projects',
    'dash.marketplace': 'Marketplace',
    'dash.rfq': 'Quotations',
    'dash.messages': 'Messages',
    'dash.notifications': 'Notifications',
    'dash.reviews': 'Reviews',
    'dash.settings': 'Settings',
    'dash.ai': 'AI Assistant',
    'dash.welcome': 'Welcome back',
    'dash.subtitle': 'Here\'s what\'s happening with your projects today.',
    'dash.active_projects': 'Active Projects',
    'dash.pending_quotes': 'Pending Quotes',
    'dash.unread_messages': 'Unread Messages',
    'dash.total_spent': 'Total Spent',
    'dash.quick_actions': 'Quick Actions',
    'dash.recent_projects': 'Recent Projects',
    'dash.view_all': 'View All',
    'dash.no_projects': 'No projects yet',
    'dash.start_project': 'Start your first project to get going.',
    'dash.create_project': 'Create Project',
    'dash.explore_market': 'Explore Marketplace',
    'dash.get_quotes': 'Get Quotes',
    'dash.ask_ai': 'Ask AI',
    'dash.send_message': 'Send Message',
    // ── Projects ─────────────────────────────────────────────────────────────
    'project.new': 'New Project',
    'project.name': 'Project Name',
    'project.type': 'Project Type',
    'project.budget': 'Total Budget',
    'project.location': 'Location',
    'project.status': 'Status',
    'project.progress': 'Progress',
    'project.milestones': 'Milestones',
    'project.documents': 'Documents',
    'project.team': 'Team',
    'project.description': 'Description',
    'project.start_date': 'Start Date',
    'project.end_date': 'End Date',
    'project.create': 'Create Project',
    'project.tasks': 'Tasks',
    'project.expenses': 'Expenses',
    'project.daily_logs': 'Daily Logs',
    'project.overview': 'Overview',
    'project.back': 'Back to Projects',
    'project.budget_used': 'Budget Used',
    'project.remaining': 'Remaining',
    'project.add_task': 'Add Task',
    'project.add_milestone': 'Add Milestone',
    'project.add_expense': 'Add Expense',
    'project.add_log': 'Add Log',
    'project.add_member': 'Add Member',
    'project.no_tasks': 'No tasks yet',
    'project.no_milestones': 'No milestones yet',
    'project.no_expenses': 'No expenses yet',
    'project.no_logs': 'No logs yet',
    'project.no_team': 'No team members yet',
    'project.priority.low': 'Low',
    'project.priority.medium': 'Medium',
    'project.priority.high': 'High',
    'project.priority.urgent': 'Urgent',
    'project.type.apartment': 'Apartment',
    'project.type.villa': 'Villa',
    'project.type.office': 'Office',
    'project.type.commercial': 'Commercial',
    'project.type.renovation': 'Renovation',
    'project.type.other': 'Other',
    // ── Marketplace ──────────────────────────────────────────────────────────
    'market.title': 'Marketplace',
    'market.subtitle': 'Browse thousands of products from verified suppliers',
    'market.search': 'Search products, brands, categories...',
    'market.filter': 'Filter',
    'market.sort': 'Sort by',
    'market.add_to_rfq': 'Add to RFQ',
    'market.view': 'View Details',
    'market.all_categories': 'All Categories',
    'market.featured': 'Featured',
    'market.in_stock': 'In Stock',
    'market.verified': 'Verified Supplier',
    'market.reviews': 'reviews',
    'market.no_products': 'No products found',
    'market.sort.popular': 'Most Popular',
    'market.sort.price_asc': 'Price: Low to High',
    'market.sort.price_desc': 'Price: High to Low',
    'market.sort.rating': 'Highest Rated',
    'market.sort.newest': 'Newest',
    // ── RFQ ──────────────────────────────────────────────────────────────────
    'rfq.title': 'Get Quotes',
    'rfq.subtitle': 'Post your requirements and receive competitive quotations from verified providers',
    'rfq.post': 'Post RFQ',
    'rfq.post.title': 'Post a Request for Quotation',
    'rfq.title_field': 'RFQ Title',
    'rfq.description': 'Describe your requirements in detail…',
    'rfq.category': 'Category',
    'rfq.budget': 'Budget (EGP)',
    'rfq.location': 'Location',
    'rfq.deadline': 'Deadline',
    'rfq.submit': 'Post RFQ',
    'rfq.submitting': 'Posting…',
    'rfq.title.placeholder': 'RFQ Title (e.g. Apartment Finishing – 150m²)',
    'rfq.description.placeholder': 'Describe your requirements in detail…',
    'rfq.no_rfqs': 'No RFQs yet',
    'rfq.no_rfqs.desc': 'Be the first to post a request for quotation!',
    'rfq.your_rfq': 'Your RFQ',
    'rfq.compare': 'Compare Quotes',
    'rfq.view_details': 'View Details',
    'rfq.status.open': 'Open',
    'rfq.status.closed': 'Closed',
    'rfq.status.awarded': 'Awarded',
    'rfq.quotations': 'quotations received',
    'rfq.best_value': 'Best Value',
    'rfq.lowest_price': 'Lowest',
    'rfq.fastest': 'Fastest',
    'rfq.match_score': 'Match Score',
    'rfq.accept': 'Accept',
    'rfq.reject': 'Reject',
    'rfq.accepting': 'Accepting…',
    'rfq.rejecting': 'Rejecting…',
    'rfq.accept.confirm.title': 'Accept Quotation?',
    'rfq.accept.confirm.desc': 'You are about to accept the quotation from {name} for {price}. All other quotations will be automatically rejected and the RFQ will be marked as awarded.',
    'rfq.reject.confirm.title': 'Reject Quotation?',
    'rfq.reject.confirm.desc': 'Are you sure you want to reject the quotation from {name}? This action can be undone by contacting support.',
    'rfq.sort.score': 'Best Score',
    'rfq.sort.price': 'Price',
    'rfq.sort.rating': 'Rating',
    'rfq.sort.timeline': 'Timeline',
    'rfq.comparison.title': 'Quotation Comparison',
    'rfq.comparison.side_by_side': 'Side-by-Side Comparison',
    'rfq.awarded_to': 'Awarded to this provider',
    'rfq.no_quotes': 'No quotations yet',
    'rfq.no_quotes.desc': 'Providers will submit their offers here once they see your RFQ.',
    // ── AI Assistant ─────────────────────────────────────────────────────────
    'ai.title': 'AI Construction Assistant',
    'ai.subtitle': 'Your intelligent partner for cost estimation, planning, and project advice',
    'ai.placeholder': 'Ask anything about your construction project…',
    'ai.send': 'Send',
    'ai.thinking': 'Thinking…',
    'ai.clear': 'Clear Chat',
    'ai.suggestions.title': 'Try asking:',
    'ai.suggestion.1': 'Estimate the cost of finishing a 150m² apartment in Cairo',
    'ai.suggestion.2': 'What materials do I need for a 200m² villa foundation?',
    'ai.suggestion.3': 'How long should a kitchen renovation take?',
    'ai.suggestion.4': 'What are the risks in a fast-track construction project?',
    'ai.suggestion.5': 'Compare marble vs ceramic flooring for a living room',
    'ai.suggestion.6': 'Create a BOQ for a 3-bedroom apartment',
    // ── Messages ─────────────────────────────────────────────────────────────
    'msg.title': 'Messages',
    'msg.search': 'Search conversations…',
    'msg.new': 'New Message',
    'msg.type': 'Type a message…',
    'msg.send': 'Send',
    'msg.notifications': 'Notifications',
    'msg.no_conversations': 'No conversations yet',
    'msg.no_conversations.desc': 'Start a conversation with a provider or homeowner.',
    'msg.no_messages': 'No messages yet',
    'msg.no_messages.desc': 'Send a message to start the conversation.',
    'msg.online': 'Online',
    'msg.offline': 'Offline',
    'msg.attach': 'Attach file',
    'msg.today': 'Today',
    'msg.yesterday': 'Yesterday',
    // ── Admin ────────────────────────────────────────────────────────────────
    'admin.title': 'Admin Control Panel',
    'admin.subtitle': 'Platform management and oversight',
    'admin.users': 'User Management',
    'admin.analytics': 'Analytics',
    'admin.disputes': 'Disputes',
    'admin.fraud': 'Fraud Detection',
    'admin.settings': 'Platform Settings',
    'admin.total_users': 'Total Users',
    'admin.total_projects': 'Total Projects',
    'admin.total_products': 'Total Products',
    'admin.total_rfqs': 'Total RFQs',
    'admin.pending_verifications': 'Pending Verifications',
    'admin.active_disputes': 'Active Disputes',
    'admin.flagged_accounts': 'Flagged Accounts',
    'admin.revenue': 'Platform Revenue',
    'admin.verify': 'Verify',
    'admin.suspend': 'Suspend',
    'admin.resolve': 'Resolve',
    'admin.dismiss': 'Dismiss',
    'admin.investigate': 'Investigate',
    'admin.user_growth': 'User Growth',
    'admin.revenue_trend': 'Revenue Trend',
    'admin.no_disputes': 'No active disputes',
    'admin.no_flagged': 'No flagged accounts',
    // ── Provider Dashboard ───────────────────────────────────────────────────
    'provider.title': 'Provider Dashboard',
    'provider.open_rfqs': 'Open RFQs',
    'provider.my_quotes': 'My Quotations',
    'provider.portfolio': 'Portfolio',
    'provider.earnings': 'Earnings',
    'provider.rating': 'Rating',
    'provider.jobs_completed': 'Jobs Completed',
    'provider.response_rate': 'Response Rate',
    'provider.submit_quote': 'Submit Quotation',
    'provider.no_rfqs': 'No open RFQs available',
    'provider.no_quotes': 'No quotations submitted yet',
    // ── Quotation form ───────────────────────────────────────────────────────
    'quote.price': 'Your Price (EGP)',
    'quote.timeline': 'Timeline (days)',
    'quote.warranty': 'Warranty',
    'quote.payment_terms': 'Payment Terms',
    'quote.notes': 'Additional Notes',
    'quote.submit': 'Submit Quotation',
    'quote.submitting': 'Submitting…',
    // ── Common ───────────────────────────────────────────────────────────────
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.close': 'Close',
    'common.add': 'Add',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.remove': 'Remove',
    'common.status.active': 'Active',
    'common.status.pending': 'Pending',
    'common.status.completed': 'Completed',
    'common.status.cancelled': 'Cancelled',
    'common.status.open': 'Open',
    'common.status.closed': 'Closed',
    'common.coming_soon': 'Coming Soon',
    'common.verified': 'Verified',
    'common.unverified': 'Unverified',
    'common.optional': 'Optional',
    'common.required': 'Required',
    'common.egp': 'EGP',
    'common.days': 'days',
    'common.sort_by': 'Sort by',
    'common.no_results': 'No results found',
    'common.try_again': 'Try again',
    'common.error': 'Something went wrong',
    'common.success': 'Success',
    'common.copied': 'Copied!',
    'common.share': 'Share',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.preview': 'Preview',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.location': 'Location',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.category': 'Category',
    'common.description': 'Description',
    'common.notes': 'Notes',
    'common.title': 'Title',
    'common.type': 'Type',
    'common.role': 'Role',
    'common.status': 'Status',
    'common.price': 'Price',
    'common.budget': 'Budget',
    'common.timeline': 'Timeline',
    'common.warranty': 'Warranty',
    'common.payment': 'Payment',
    'common.rating': 'Rating',
    'common.reviews': 'Reviews',
    'common.score': 'Score',
    'common.accepted': 'Accepted',
    'common.rejected': 'Rejected',
    'common.pending': 'Pending',
    'common.awarded': 'Awarded',
    'common.status.on_hold': 'On Hold',
    'common.status.in_progress': 'In Progress',
    'common.status.planning': 'Planning',
    'common.status.awarded': 'Awarded',
    'common.sign_in_to': 'Sign in to access',
    'common.sign_in': 'Sign In',
    'common.sign_in_desc': 'Please sign in to access this feature.',
    'dash.portfolio': 'Portfolio',
    'dash.earnings': 'Earnings',
    'dash.team': 'Team',
    'dash.admin': 'Admin Panel',
    'dash.sign_out': 'Sign Out',
    'dash.profile': 'Profile',
    'dash.provider': 'Provider Dashboard',
    'admin.verifications': 'Verifications',
    'admin.platform_stats': 'Platform Stats',
    'admin.recent_users': 'Recent Users',
    'admin.actions': 'Actions',
    'admin.verified': 'Verified',
    'admin.suspended': 'Suspended',
    'admin.active': 'Active',
    'provider.available': 'Available for Work',
    'provider.profile': 'My Profile',
    'provider.reviews': 'Reviews',
    'platform.homeowner.title': 'Homeowner Workspace',
    'platform.homeowner.subtitle': 'Plan your projects, control budgets, and choose the right professionals.',
    'platform.contractor.title': 'Contractor Workspace',
    'platform.contractor.subtitle': 'Turn qualified requests into profitable, well-managed work.',
    'platform.engineer.title': 'Engineering Workspace',
    'platform.engineer.subtitle': 'Coordinate technical delivery, documents, and project decisions.',
    'platform.architect.title': 'Architecture Workspace',
    'platform.architect.subtitle': 'Present your design expertise and collaborate from concept to delivery.',
    'platform.supplier.title': 'Supplier Workspace',
    'platform.supplier.subtitle': 'List products, respond to demand, and grow your construction catalogue.',
    'platform.project_manager.title': 'Project Management Workspace',
    'platform.project_manager.subtitle': 'Orchestrate milestones, teams, budgets, and delivery across projects.',
    'platform.workspace': 'Workspace',
    'platform.pipeline': 'Pipeline',
    'platform.catalogue': 'Catalogue',
    'platform.projects': 'Projects',
    'platform.documents': 'Documents',
    'platform.team': 'Team',
    'platform.performance': 'Performance',
    'platform.new_listing': 'New Product Listing',
    'platform.review_requests': 'Review RFQs',
    'platform.create_quote': 'Create Quotation',
    'platform.new_project': 'New Project',
    'platform.portfolio': 'Portfolio',
    'platform.add_service': 'Add Service',
    'platform.project_queue': 'Project Queue',
    'platform.recent_activity': 'Recent Activity',
    'platform.no_items': 'No items yet',
    'platform.open': 'Open',
    'platform.view': 'View',
    'platform.manage': 'Manage',
    'ai.capabilities': 'AI Capabilities',
    'ai.cost_estimation': 'Cost Estimation',
    'ai.cost_estimation.desc': 'Get instant AI-powered cost estimates for your construction project.',
    'ai.qty_surveying': 'Quantity Surveying',
    'ai.qty_surveying.desc': 'Calculate materials, quantities, and BOQ for any project type.',
    'ai.material_rec': 'Material Recommendations',
    'ai.material_rec.desc': 'Get expert suggestions for materials based on your budget and location.',
    'ai.risk_detection': 'Risk Detection',
    'ai.risk_detection.desc': 'Identify potential risks and delays before they happen.',
    'ai.pm_advice': 'Project Management Advice',
    'ai.pm_advice.desc': 'Get guidance on scheduling, team management, and best practices.',
    'ai.regulations': 'Regulations & Permits',
    'ai.regulations.desc': 'Understand local building codes, permits, and compliance requirements.',
  },
  ar: {
    // ── Nav ──────────────────────────────────────────────────────────────────
    'nav.home': 'الرئيسية',
    'nav.marketplace': 'السوق',
    'nav.projects': 'المشاريع',
    'nav.rfq': 'طلب عروض',
    'nav.signin': 'تسجيل الدخول',
    'nav.signup': 'ابدأ الآن',
    'nav.dashboard': 'لوحة التحكم',
    'nav.logout': 'تسجيل الخروج',
    'nav.messages': 'الرسائل',
    'nav.notifications': 'الإشعارات',
    'nav.admin': 'لوحة الإدارة',
    'nav.ai': 'مساعد الذكاء الاصطناعي',
    // ── Hero ─────────────────────────────────────────────────────────────────
    'hero.badge': 'نظام تشغيل البناء بالذكاء الاصطناعي',
    'hero.title': 'ابنِ بذكاء. اربط الجميع.',
    'hero.subtitle': 'BuildHub يربط أصحاب المنازل والمقاولين والمهندسين والمعماريين والموردين في منظومة ذكية واحدة — من التخطيط حتى الإنجاز.',
    'hero.cta.primary': 'ابدأ مشروعك',
    'hero.cta.secondary': 'استكشف السوق',
    // ── Stats ────────────────────────────────────────────────────────────────
    'stats.users': 'مستخدم مسجل',
    'stats.projects': 'مشروع نشط',
    'stats.providers': 'مزود موثق',
    'stats.satisfaction': 'معدل الرضا',
    // ── Features ─────────────────────────────────────────────────────────────
    'features.badge': 'المميزات',
    'features.title': 'كل ما تحتاجه للبناء',
    'features.subtitle': 'منصة واحدة لكل مرحلة من رحلة البناء',
    'features.marketplace.title': 'سوق ذكي',
    'features.marketplace.desc': 'تصفح آلاف المنتجات من مواد البناء والأثاث وأنظمة التكييف وغيرها مع مواصفات كاملة وتقييمات موثقة.',
    'features.rfq.title': 'محرك طلبات العروض',
    'features.rfq.desc': 'انشر متطلباتك واحصل على عروض تنافسية من مزودين موثقين، ثم قارن بينها جنباً إلى جنب.',
    'features.ai.title': 'مجموعة مساعد الذكاء الاصطناعي',
    'features.ai.desc': 'احصل على تقديرات تكلفة فورية وكميات ومواد موصى بها وتقييمات مخاطر مدعومة بالذكاء الاصطناعي.',
    'features.pm.title': 'إدارة المشاريع',
    'features.pm.desc': 'تتبع الجداول الزمنية والمعالم والميزانيات ومهام الفريق في مساحة عمل موحدة مصممة للبناء.',
    'features.matching.title': 'المطابقة الذكية',
    'features.matching.desc': 'تعرض خوارزميتنا أفضل المقاولين والموردين بناءً على الموقع والتقييمات وميزانيتك.',
    'features.messaging.title': 'التعاون الفوري',
    'features.messaging.desc': 'تحدث وشارك الملفات وتبادل العروض واحصل على إشعارات فورية — كل ذلك داخل المنصة.',
    // ── How it works ─────────────────────────────────────────────────────────
    'how.badge': 'كيف يعمل',
    'how.title': 'من الفكرة إلى الإنجاز في 4 خطوات',
    'how.step1.title': 'أنشئ مشروعك',
    'how.step1.desc': 'حدد نطاق مشروعك وميزانيتك وجدولك الزمني. ارفع الرسومات وجداول الكميات.',
    'how.step2.title': 'انشر طلب عرض',
    'how.step2.desc': 'صف متطلباتك واحصل على عروض تنافسية من مزودين موثقين.',
    'how.step3.title': 'قارن واختر',
    'how.step3.desc': 'قارن المزودين جنباً إلى جنب على السعر والجدول الزمني والتقييم والخبرة.',
    'how.step4.title': 'أدر وأنجز',
    'how.step4.desc': 'تتبع التقدم وأدر المدفوعات وتواصل مع فريقك وأنجز مشروعك.',
    // ── Roles ────────────────────────────────────────────────────────────────
    'roles.badge': 'لمن هذه المنصة',
    'roles.title': 'مبني لكل أصحاب المصلحة',
    'roles.homeowner': 'صاحب المنزل',
    'roles.homeowner.desc': 'أنشئ مشاريع وأدر الميزانيات واستأجر المحترفين وتتبع التقدم من لوحة تحكم واحدة.',
    'roles.homeowner.cta': 'ابدأ كصاحب منزل',
    'roles.contractor': 'المقاول',
    'roles.contractor.desc': 'استقبل طلبات العروض وقدم العطاءات وأدر فريقك وطوّر أعمالك.',
    'roles.contractor.cta': 'انضم كمقاول',
    'roles.engineer': 'المهندس',
    'roles.engineer.desc': 'اعرض خبرتك وتعاون في المشاريع وأدر محفظتك.',
    'roles.engineer.cta': 'انضم كمهندس',
    'roles.architect': 'المعماري',
    'roles.architect.desc': 'قدّم تصاميمك وتواصل مع العملاء وأدر وثائق المشروع.',
    'roles.architect.cta': 'انضم كمعماري',
    'roles.supplier': 'المورد',
    'roles.supplier.desc': 'اعرض منتجاتك واستقبل الطلبات وتواصل مع آلاف المحترفين في البناء.',
    'roles.supplier.cta': 'انضم كمورد',
    'roles.pm': 'مدير المشروع',
    'roles.pm.desc': 'أشرف على مشاريع متعددة ونسّق الفرق وسلّم في الوقت والميزانية المحددين.',
    'roles.pm.cta': 'انضم كمدير مشروع',
    // ── Testimonials ─────────────────────────────────────────────────────────
    'testimonials.badge': 'آراء العملاء',
    'testimonials.title': 'موثوق به من الآلاف',
    'testimonials.subtitle': 'اطلع على ما يقوله مستخدمونا عن BuildHub',
    'testimonials.1.text': 'وفّر لي BuildHub أسابيع من البحث عن المقاولين. المقارنة الجانبية جعلت الاختيار سهلاً جداً.',
    'testimonials.1.name': 'ليلى أحمد',
    'testimonials.1.role': 'صاحبة منزل، القاهرة',
    'testimonials.2.text': 'كمقاول، يجلب لي محرك طلبات العروض عملاء مؤهلين كل أسبوع. نمت أعمالي بنسبة 40% منذ الانضمام.',
    'testimonials.2.name': 'خالد مصطفى',
    'testimonials.2.role': 'مقاول عام، الإسكندرية',
    'testimonials.3.text': 'مقدّر التكلفة بالذكاء الاصطناعي دقيق بشكل لا يصدق. أصبح الآن أول أداة أستخدمها في كل مشروع جديد.',
    'testimonials.3.name': 'نور حسن',
    'testimonials.3.role': 'مهندس مدني، الجيزة',
    // ── CTA Banner ───────────────────────────────────────────────────────────
    'cta.title': 'هل أنت مستعد للبناء بذكاء؟',
    'cta.subtitle': 'انضم إلى آلاف أصحاب المنازل والمقاولين والمحترفين الذين يستخدمون BuildHub بالفعل.',
    'cta.primary': 'ابدأ مجاناً',
    'cta.secondary': 'اعرف المزيد',
    // ── Footer ───────────────────────────────────────────────────────────────
    'footer.tagline': 'نظام تشغيل البناء بالذكاء الاصطناعي للشرق الأوسط.',
    'footer.platform': 'المنصة',
    'footer.company': 'الشركة',
    'footer.support': 'الدعم',
    'footer.about': 'من نحن',
    'footer.careers': 'وظائف',
    'footer.blog': 'المدونة',
    'footer.press': 'الصحافة',
    'footer.help': 'مركز المساعدة',
    'footer.contact': 'اتصل بنا',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.rights': 'جميع الحقوق محفوظة.',
    // ── Auth ─────────────────────────────────────────────────────────────────
    'auth.signin': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.role.select': 'أنا...',
    'auth.role.prompt': 'اختر دورك للبدء',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.name': 'الاسم الكامل',
    'auth.phone': 'رقم الهاتف',
    'auth.otp': 'رمز التحقق',
    'auth.otp.sent': 'أرسلنا رمزاً مكوناً من 6 أرقام إلى هاتفك',
    'auth.continue': 'متابعة',
    'auth.complete_setup': 'إكمال الإعداد',
    'auth.have.account': 'لديك حساب بالفعل؟',
    'auth.no.account': 'ليس لديك حساب؟',
    'auth.welcome': 'مرحباً بك في BuildHub',
    'auth.tagline': 'الطريقة الأذكى للبناء',
    'auth.or': 'أو تابع بـ',
    'auth.forgot': 'نسيت كلمة المرور؟',
    // ── Dashboard ────────────────────────────────────────────────────────────
    'dash.overview': 'نظرة عامة',
    'dash.projects': 'مشاريعي',
    'dash.marketplace': 'السوق',
    'dash.rfq': 'عروض الأسعار',
    'dash.messages': 'الرسائل',
    'dash.notifications': 'الإشعارات',
    'dash.reviews': 'التقييمات',
    'dash.settings': 'الإعدادات',
    'dash.ai': 'مساعد الذكاء الاصطناعي',
    'dash.welcome': 'مرحباً بعودتك',
    'dash.subtitle': 'إليك ما يحدث في مشاريعك اليوم.',
    'dash.active_projects': 'مشاريع نشطة',
    'dash.pending_quotes': 'عروض معلقة',
    'dash.unread_messages': 'رسائل غير مقروءة',
    'dash.total_spent': 'إجمالي الإنفاق',
    'dash.quick_actions': 'إجراءات سريعة',
    'dash.recent_projects': 'المشاريع الأخيرة',
    'dash.view_all': 'عرض الكل',
    'dash.no_projects': 'لا توجد مشاريع بعد',
    'dash.start_project': 'ابدأ مشروعك الأول للانطلاق.',
    'dash.create_project': 'إنشاء مشروع',
    'dash.explore_market': 'استكشف السوق',
    'dash.get_quotes': 'احصل على عروض',
    'dash.ask_ai': 'اسأل الذكاء الاصطناعي',
    'dash.send_message': 'إرسال رسالة',
    // ── Projects ─────────────────────────────────────────────────────────────
    'project.new': 'مشروع جديد',
    'project.name': 'اسم المشروع',
    'project.type': 'نوع المشروع',
    'project.budget': 'الميزانية الإجمالية',
    'project.location': 'الموقع',
    'project.status': 'الحالة',
    'project.progress': 'التقدم',
    'project.milestones': 'المعالم',
    'project.documents': 'الوثائق',
    'project.team': 'الفريق',
    'project.description': 'الوصف',
    'project.start_date': 'تاريخ البدء',
    'project.end_date': 'تاريخ الانتهاء',
    'project.create': 'إنشاء مشروع',
    'project.tasks': 'المهام',
    'project.expenses': 'المصروفات',
    'project.daily_logs': 'السجلات اليومية',
    'project.overview': 'نظرة عامة',
    'project.back': 'العودة إلى المشاريع',
    'project.budget_used': 'الميزانية المستخدمة',
    'project.remaining': 'المتبقي',
    'project.add_task': 'إضافة مهمة',
    'project.add_milestone': 'إضافة معلم',
    'project.add_expense': 'إضافة مصروف',
    'project.add_log': 'إضافة سجل',
    'project.add_member': 'إضافة عضو',
    'project.no_tasks': 'لا توجد مهام بعد',
    'project.no_milestones': 'لا توجد معالم بعد',
    'project.no_expenses': 'لا توجد مصروفات بعد',
    'project.no_logs': 'لا توجد سجلات بعد',
    'project.no_team': 'لا يوجد أعضاء فريق بعد',
    'project.priority.low': 'منخفضة',
    'project.priority.medium': 'متوسطة',
    'project.priority.high': 'عالية',
    'project.priority.urgent': 'عاجلة',
    'project.type.apartment': 'شقة',
    'project.type.villa': 'فيلا',
    'project.type.office': 'مكتب',
    'project.type.commercial': 'تجاري',
    'project.type.renovation': 'تجديد',
    'project.type.other': 'أخرى',
    // ── Marketplace ──────────────────────────────────────────────────────────
    'market.title': 'السوق',
    'market.subtitle': 'تصفح آلاف المنتجات من موردين موثقين',
    'market.search': 'ابحث عن منتجات، علامات تجارية، فئات...',
    'market.filter': 'تصفية',
    'market.sort': 'ترتيب حسب',
    'market.add_to_rfq': 'أضف لطلب العرض',
    'market.view': 'عرض التفاصيل',
    'market.all_categories': 'جميع الفئات',
    'market.featured': 'مميز',
    'market.in_stock': 'متوفر',
    'market.verified': 'مورد موثق',
    'market.reviews': 'تقييم',
    'market.no_products': 'لم يتم العثور على منتجات',
    'market.sort.popular': 'الأكثر شعبية',
    'market.sort.price_asc': 'السعر: من الأقل للأعلى',
    'market.sort.price_desc': 'السعر: من الأعلى للأقل',
    'market.sort.rating': 'الأعلى تقييماً',
    'market.sort.newest': 'الأحدث',
    // ── RFQ ──────────────────────────────────────────────────────────────────
    'rfq.title': 'طلب عروض',
    'rfq.subtitle': 'انشر متطلباتك واحصل على عروض تنافسية من مزودين موثقين',
    'rfq.post': 'نشر طلب عرض',
    'rfq.post.title': 'نشر طلب عرض سعر',
    'rfq.title_field': 'عنوان الطلب',
    'rfq.description': 'صف متطلباتك بالتفصيل…',
    'rfq.category': 'الفئة',
    'rfq.budget': 'الميزانية (جنيه)',
    'rfq.location': 'الموقع',
    'rfq.deadline': 'الموعد النهائي',
    'rfq.submit': 'نشر الطلب',
    'rfq.submitting': 'جاري النشر…',
    'rfq.title.placeholder': 'عنوان الطلب (مثال: تشطيب شقة 150م²)',
    'rfq.description.placeholder': 'صف متطلباتك بالتفصيل…',
    'rfq.no_rfqs': 'لا توجد طلبات بعد',
    'rfq.no_rfqs.desc': 'كن أول من ينشر طلب عرض سعر!',
    'rfq.your_rfq': 'طلبك',
    'rfq.compare': 'مقارنة العروض',
    'rfq.view_details': 'عرض التفاصيل',
    'rfq.status.open': 'مفتوح',
    'rfq.status.closed': 'مغلق',
    'rfq.status.awarded': 'تم الترسية',
    'rfq.quotations': 'عرض مستلم',
    'rfq.best_value': 'أفضل قيمة',
    'rfq.lowest_price': 'الأقل سعراً',
    'rfq.fastest': 'الأسرع',
    'rfq.match_score': 'درجة التطابق',
    'rfq.accept': 'قبول',
    'rfq.reject': 'رفض',
    'rfq.accepting': 'جاري القبول…',
    'rfq.rejecting': 'جاري الرفض…',
    'rfq.accept.confirm.title': 'قبول العرض؟',
    'rfq.accept.confirm.desc': 'أنت على وشك قبول العرض من {name} بسعر {price}. سيتم رفض جميع العروض الأخرى تلقائياً وسيُعلَّم الطلب كمُرسى.',
    'rfq.reject.confirm.title': 'رفض العرض؟',
    'rfq.reject.confirm.desc': 'هل أنت متأكد من رفض العرض من {name}؟ يمكن التراجع عن هذا الإجراء بالتواصل مع الدعم.',
    'rfq.sort.score': 'أفضل درجة',
    'rfq.sort.price': 'السعر',
    'rfq.sort.rating': 'التقييم',
    'rfq.sort.timeline': 'الجدول الزمني',
    'rfq.comparison.title': 'مقارنة العروض',
    'rfq.comparison.side_by_side': 'مقارنة جانبية',
    'rfq.awarded_to': 'تم الترسية على هذا المزود',
    'rfq.no_quotes': 'لا توجد عروض بعد',
    'rfq.no_quotes.desc': 'سيقدم المزودون عروضهم هنا بمجرد رؤية طلبك.',
    // ── AI Assistant ─────────────────────────────────────────────────────────
    'ai.title': 'مساعد البناء بالذكاء الاصطناعي',
    'ai.subtitle': 'شريكك الذكي لتقدير التكاليف والتخطيط ونصائح المشاريع',
    'ai.placeholder': 'اسأل أي شيء عن مشروع البناء الخاص بك…',
    'ai.send': 'إرسال',
    'ai.thinking': 'جاري التفكير…',
    'ai.clear': 'مسح المحادثة',
    'ai.suggestions.title': 'جرب أن تسأل:',
    'ai.suggestion.1': 'قدّر تكلفة تشطيب شقة 150 متر في القاهرة',
    'ai.suggestion.2': 'ما المواد التي أحتاجها لأساس فيلا 200 متر؟',
    'ai.suggestion.3': 'كم يستغرق تجديد مطبخ؟',
    'ai.suggestion.4': 'ما هي مخاطر مشروع البناء السريع؟',
    'ai.suggestion.5': 'قارن بين الرخام والسيراميك لغرفة المعيشة',
    'ai.suggestion.6': 'أنشئ جدول كميات لشقة 3 غرف نوم',
    // ── Messages ─────────────────────────────────────────────────────────────
    'msg.title': 'الرسائل',
    'msg.search': 'ابحث في المحادثات…',
    'msg.new': 'رسالة جديدة',
    'msg.type': 'اكتب رسالة…',
    'msg.send': 'إرسال',
    'msg.notifications': 'الإشعارات',
    'msg.no_conversations': 'لا توجد محادثات بعد',
    'msg.no_conversations.desc': 'ابدأ محادثة مع مزود أو صاحب منزل.',
    'msg.no_messages': 'لا توجد رسائل بعد',
    'msg.no_messages.desc': 'أرسل رسالة لبدء المحادثة.',
    'msg.online': 'متصل',
    'msg.offline': 'غير متصل',
    'msg.attach': 'إرفاق ملف',
    'msg.today': 'اليوم',
    'msg.yesterday': 'أمس',
    // ── Admin ────────────────────────────────────────────────────────────────
    'admin.title': 'لوحة التحكم الإدارية',
    'admin.subtitle': 'إدارة المنصة والإشراف عليها',
    'admin.users': 'إدارة المستخدمين',
    'admin.analytics': 'التحليلات',
    'admin.disputes': 'النزاعات',
    'admin.fraud': 'كشف الاحتيال',
    'admin.settings': 'إعدادات المنصة',
    'admin.total_users': 'إجمالي المستخدمين',
    'admin.total_projects': 'إجمالي المشاريع',
    'admin.total_products': 'إجمالي المنتجات',
    'admin.total_rfqs': 'إجمالي طلبات العروض',
    'admin.pending_verifications': 'التحققات المعلقة',
    'admin.active_disputes': 'النزاعات النشطة',
    'admin.flagged_accounts': 'الحسابات المُبلَّغ عنها',
    'admin.revenue': 'إيرادات المنصة',
    'admin.verify': 'توثيق',
    'admin.suspend': 'تعليق',
    'admin.resolve': 'حل',
    'admin.dismiss': 'رفض',
    'admin.investigate': 'تحقيق',
    'admin.user_growth': 'نمو المستخدمين',
    'admin.revenue_trend': 'اتجاه الإيرادات',
    'admin.no_disputes': 'لا توجد نزاعات نشطة',
    'admin.no_flagged': 'لا توجد حسابات مُبلَّغ عنها',
    // ── Provider Dashboard ───────────────────────────────────────────────────
    'provider.title': 'لوحة تحكم المزود',
    'provider.open_rfqs': 'طلبات العروض المفتوحة',
    'provider.my_quotes': 'عروضي المقدمة',
    'provider.portfolio': 'المحفظة',
    'provider.earnings': 'الأرباح',
    'provider.rating': 'التقييم',
    'provider.jobs_completed': 'الأعمال المنجزة',
    'provider.response_rate': 'معدل الاستجابة',
    'provider.submit_quote': 'تقديم عرض',
    'provider.no_rfqs': 'لا توجد طلبات عروض مفتوحة',
    'provider.no_quotes': 'لم يتم تقديم أي عروض بعد',
    // ── Quotation form ───────────────────────────────────────────────────────
    'quote.price': 'سعرك (جنيه)',
    'quote.timeline': 'الجدول الزمني (أيام)',
    'quote.warranty': 'الضمان',
    'quote.payment_terms': 'شروط الدفع',
    'quote.notes': 'ملاحظات إضافية',
    'quote.submit': 'تقديم العرض',
    'quote.submitting': 'جاري التقديم…',
    // ── Common ───────────────────────────────────────────────────────────────
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.submit': 'إرسال',
    'common.loading': 'جاري التحميل...',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.all': 'الكل',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.confirm': 'تأكيد',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.close': 'إغلاق',
    'common.add': 'إضافة',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.remove': 'إزالة',
    'common.status.active': 'نشط',
    'common.status.pending': 'قيد الانتظار',
    'common.status.completed': 'مكتمل',
    'common.status.cancelled': 'ملغي',
    'common.status.open': 'مفتوح',
    'common.status.closed': 'مغلق',
    'common.coming_soon': 'قريباً',
    'common.verified': 'موثق',
    'common.unverified': 'غير موثق',
    'common.optional': 'اختياري',
    'common.required': 'مطلوب',
    'common.egp': 'جنيه',
    'common.days': 'يوم',
    'common.sort_by': 'ترتيب حسب',
    'common.no_results': 'لا توجد نتائج',
    'common.try_again': 'حاول مرة أخرى',
    'common.error': 'حدث خطأ ما',
    'common.success': 'تم بنجاح',
    'common.copied': 'تم النسخ!',
    'common.share': 'مشاركة',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.preview': 'معاينة',
    'common.actions': 'إجراءات',
    'common.details': 'تفاصيل',
    'common.name': 'الاسم',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.location': 'الموقع',
    'common.date': 'التاريخ',
    'common.amount': 'المبلغ',
    'common.category': 'الفئة',
    'common.description': 'الوصف',
    'common.notes': 'ملاحظات',
    'common.title': 'العنوان',
    'common.type': 'النوع',
    'common.role': 'الدور',
    'common.status': 'الحالة',
    'common.price': 'السعر',
    'common.budget': 'الميزانية',
    'common.timeline': 'الجدول الزمني',
    'common.warranty': 'الضمان',
    'common.payment': 'الدفع',
    'common.rating': 'التقييم',
    'common.reviews': 'التقييمات',
    'common.score': 'الدرجة',
    'common.accepted': 'مقبول',
    'common.rejected': 'مرفوض',
    'common.pending': 'قيد الانتظار',
    'common.awarded': 'تم الترسية',
    'common.status.on_hold': 'معلق',
    'common.status.in_progress': 'قيد التنفيذ',
    'common.status.planning': 'تخطيط',
    'common.status.awarded': 'تم الترسية',
    'common.sign_in_to': 'سجّل الدخول للوصول',
    'common.sign_in': 'تسجيل الدخول',
    'common.sign_in_desc': 'يرجى تسجيل الدخول للوصول إلى هذه الميزة.',
    'dash.portfolio': 'المحفظة',
    'dash.earnings': 'الأرباح',
    'dash.team': 'الفريق',
    'dash.admin': 'لوحة الإدارة',
    'dash.sign_out': 'تسجيل الخروج',
    'dash.profile': 'الملف الشخصي',
    'dash.provider': 'لوحة تحكم المزود',
    'admin.verifications': 'التحققات',
    'admin.platform_stats': 'إحصائيات المنصة',
    'admin.recent_users': 'المستخدمون الأخيرون',
    'admin.actions': 'الإجراءات',
    'admin.verified': 'موثق',
    'admin.suspended': 'معلق',
    'admin.active': 'نشط',
    'provider.available': 'متاح للعمل',
    'provider.profile': 'ملفي الشخصي',
    'provider.reviews': 'التقييمات',
    'platform.homeowner.title': 'مساحة مالك المنزل',
    'platform.homeowner.subtitle': 'خطط لمشاريعك وتحكم في الميزانيات واختر المتخصصين المناسبين.',
    'platform.contractor.title': 'مساحة المقاول',
    'platform.contractor.subtitle': 'حوّل الطلبات المؤهلة إلى أعمال مربحة ومدارة بكفاءة.',
    'platform.engineer.title': 'مساحة المهندس',
    'platform.engineer.subtitle': 'نسّق التنفيذ الفني والمستندات وقرارات المشروع.',
    'platform.architect.title': 'مساحة المهندس المعماري',
    'platform.architect.subtitle': 'اعرض خبرتك التصميمية وتعاون من الفكرة حتى التنفيذ.',
    'platform.supplier.title': 'مساحة المورد',
    'platform.supplier.subtitle': 'أدرج منتجاتك واستجب للطلب ونمِّ كتالوجك الإنشائي.',
    'platform.project_manager.title': 'مساحة مدير المشروع',
    'platform.project_manager.subtitle': 'أدر المراحل والفرق والميزانيات والتسليم عبر مشاريعك.',
    'platform.workspace': 'مساحة العمل',
    'platform.pipeline': 'مسار الأعمال',
    'platform.catalogue': 'الكتالوج',
    'platform.projects': 'المشاريع',
    'platform.documents': 'المستندات',
    'platform.team': 'الفريق',
    'platform.performance': 'الأداء',
    'platform.new_listing': 'إضافة منتج جديد',
    'platform.review_requests': 'مراجعة طلبات الأسعار',
    'platform.create_quote': 'إنشاء عرض سعر',
    'platform.new_project': 'مشروع جديد',
    'platform.portfolio': 'معرض الأعمال',
    'platform.add_service': 'إضافة خدمة',
    'platform.project_queue': 'قائمة المشاريع',
    'platform.recent_activity': 'النشاط الأخير',
    'platform.no_items': 'لا توجد عناصر بعد',
    'platform.open': 'مفتوح',
    'platform.view': 'عرض',
    'platform.manage': 'إدارة',
    'ai.capabilities': 'قدرات الذكاء الاصطناعي',
    'ai.cost_estimation': 'تقدير التكاليف',
    'ai.cost_estimation.desc': 'احصل على تقديرات تكلفة فورية بالذكاء الاصطناعي لمشروع البناء الخاص بك.',
    'ai.qty_surveying': 'حصر الكميات',
    'ai.qty_surveying.desc': 'احسب المواد والكميات وجداول الكميات لأي نوع من المشاريع.',
    'ai.material_rec': 'توصيات المواد',
    'ai.material_rec.desc': 'احصل على اقتراحات خبراء للمواد بناءً على ميزانيتك وموقعك.',
    'ai.risk_detection': 'كشف المخاطر',
    'ai.risk_detection.desc': 'حدد المخاطر والتأخيرات المحتملة قبل حدوثها.',
    'ai.pm_advice': 'نصائح إدارة المشاريع',
    'ai.pm_advice.desc': 'احصل على إرشادات حول الجدولة وإدارة الفريق وأفضل الممارسات.',
    'ai.regulations': 'اللوائح والتصاريح',
    'ai.regulations.desc': 'تعرف على قوانين البناء المحلية والتصاريح ومتطلبات الامتثال.',
  },
};

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'en',
  dir: 'ltr',
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('buildhub_lang') as Language) || 'en';
  });

  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem('buildhub_lang', l);
  };

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
    document.body.style.fontFamily = lang === 'ar' ? "'Cairo', sans-serif" : "'Inter', sans-serif";
  }, [lang, dir]);

  const t = (key: string): string => {
    return translations[lang][key] ?? translations['en'][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, dir, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
